### ISSUE TITLE
Jamaica test data fails with ogr2osm error

### ISSUE THREAD

**Issue by stvno** [WorldBank-Transport/Rural-Road-Accessibility#112]
6cabba0  works for me with the sergipe test data, but when I tried to run it with @brunosan 's Jamaica testdata it fails with a ogr2osm error:

`Traceback (most recent call last): File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 750, in <module> parseData(data) File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 346, in parseData parseLayer(translations.filterLayer(layer)) File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 410, in parseLayer parseFeature(translations.filterFeature(ogrfeature, fieldNames, reproject), fieldNames, reproject) File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 420, in parseFeature geometries = parseGeometry([ogrgeometry]) File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 458, in parseGeometry returngeometries.extend(parseCollection(ogrgeometry)) File "/home/steven/src/Rural-Road-Accessibility/app/lib/ogr2osm/ogr2osm.py", line 545, in parseCollection member.addparent(geometry) AttributeError: 'list' object has no attribute 'addparent'
`

Unlike the Sergipe OSM file, the Jamaica OSM file contains more than just the road-network. I've created a new branch `jm-test` and put the data in test/utils/data-jamaica.

**Comment by danielfdsilva** [comment]
@olafveerman data here https://github.com/WorldBank-Transport/Rural-Road-Accessibility/tree/jm-test/test/utils/data-jamaica

**Comment by olafveerman** [comment]
@stvno @danielfdsilva 
It fails on the relations in the OSM file, though I'm not sure why.
When processing the road network, would it make sense to filter out any feature that's not a way?

**Comment by olafveerman** [comment]
For the record, I was able to generate the following results by removing the relations from the initial OSM file:

![image](https://cloud.githubusercontent.com/assets/751330/25821240/5394289e-3402-11e7-8af0-6701f5d02aae.png)

**Comment by danielfdsilva** [comment]
@olafveerman What POIs did you use? I used banks on my tests and obviously the values are different.

Btw, for the result generation, relations have no effect.
