### ISSUE TITLE
Fingeprint does not match 

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#29]
Stuck on running #28 with a `Fingeprint does not match`

I think it might be related to `node-osrm` and `osrm-backend` not pulling from the same versions, but I've tried as documented on [the docs](https://github.com/Project-OSRM/node-osrm#using-an-existing-local-osrm-backend)

```js
/Users/brunosan/code/Rural-Road-Accessibility/scripts/node/calculateETA.js:19
	var osrm = new OSRM(e.osrm);
	           ^

TypeError: Fingeprint does not match in /Users/brunosan/code/Rural-Road-Accessibility/./web/data/project_1463767649122/baseline/JM.osrm.icd
    at TypeError (native)
    at process.<anonymous> (/Users/brunosan/code/Rural-Road-Accessibility/scripts/node/calculateETA.js:19:13)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at processEmit [as emit] (/Users/brunosan/code/Rural-Road-Accessibility/node_modules/osrm/node_modules/node-pre-gyp/node_modules/npmlog/node_modules/gauge/node_modules/signal-exit/index.js:146:32)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

Investigating...

**Comment by brunosan** [comment]
Yeap that was the problem. I only had to regenerate the `.osrm*` files after pulling the latests `osrm-backend` code, building, and building `node-osrm` against it.
