### ISSUE TITLE
Villages need to be points

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#36]
If they are regions, `@turf/within` will fails:

```js
    throw new Error('A coordinate, feature, or point geometry is required');
    ^

Error: A coordinate, feature, or point geometry is required
    at Object.getCoord (/Users/brunosan/code/Rural-Road-Accessibility/node_modules/@turf/invariant/index.js:24:11)
    at input (/Users/brunosan/code/Rural-Road-Accessibility/node_modules/@turf/inside/index.js:30:24)
    at module.exports (/Users/brunosan/code/Rural-Road-Accessibility/node_modules/@turf/within/index.js:87:28)
    at villagesInRegion (/Users/brunosan/code/Rural-Road-Accessibility/scripts/node/calculateETA.js:186:15)
```

<img width="534" alt="screen shot 2016-11-30 at 4 21 27 pm" src="https://cloud.githubusercontent.com/assets/434029/20771841/25e2cfa6-b719-11e6-9c59-56fe40dca35d.png">

Either convert first all `villages.geojson` to points, or calculate it on runtine.

**Comment by brunosan** [comment]
Leaving this open, in case it is still relevant on `v0.2.0` branch

**Comment by danielfdsilva** [comment]
For villages that are not points the centroid is calculated
